import type { ScenarioPack } from '../contracts/scenarioPack.ts'

export const indoPakScenarioPack = {
  schemaVersion: 'ise-scenario-pack/v1', packId: 'indo-pak-air-combat/v1', version: '1', displayName: 'Indo-Pak Air Combat',
  matchRules: [{ ruleId: 'indo-pak-explicit-platform-and-location/v1', entityAliases: ['Su-30MKI', '苏-30MKI', 'Rafale', '阵风', 'JF-17', 'JF17', 'Netra AEW&CS', 'Saab 2000 Erieye', 'ZDK-03'], locationAliases: ['Adampur', '阿达姆普尔', 'Ambala', '安巴拉', 'Minhas', 'Minas', '米纳斯', 'Rafiki', '拉菲基'], minimumScore: 2 }],
  factions: [{ factionId: 'india', aliases: ['India', '印方'], displayName: 'India' }, { factionId: 'pakistan', aliases: ['Pakistan', '巴方'], displayName: 'Pakistan' }],
  entityProfiles: [
    { entityId: 'su30mki', aliases: ['Su-30MKI', '苏-30MKI'], platformKind: 'aircraft', modelAssetAliases: ['model:su30mki'] },
    { entityId: 'rafale', aliases: ['Rafale', '阵风'], platformKind: 'aircraft', modelAssetAliases: ['model:rafale'] },
    { entityId: 'jf17', aliases: ['JF-17', 'JF17'], platformKind: 'aircraft', modelAssetAliases: ['model:jf17'] },
  ],
  locationProfiles: [{ locationId: 'location:adampur', aliases: ['Adampur', '阿达姆普尔'], coordinates: [75.66, 31.43] }, { locationId: 'location:ambala', aliases: ['Ambala', '安巴拉'], coordinates: [76.82, 30.37] }, { locationId: 'location:minhas', aliases: ['Minhas', 'Minas', '米纳斯'], coordinates: [73.10, 33.87] }, { locationId: 'location:rafiki', aliases: ['Rafiki', '拉菲基'], coordinates: [72.99, 31.36] }],
  routeBundles: [
    { bundleId: 'formation:india-su30-adampur', modelAssetRef: 'model:su30mki', routeAssetRefs: ['trajectory:adampur-vampire-1', 'trajectory:adampur-vampire-2', 'trajectory:adampur-vampire-3', 'trajectory:adampur-vampire-4'], semanticEntityAliases: ['Su-30MKI', 'Su-30MKI编队', '苏-30MKI', '苏-30MKI编队'], behaviorProfileRefs: ['fighter-formation/v1'], locationRefs: ['location:adampur', 'ADAMPUR', 'Adampur', '阿达姆普尔'], diagnostics: ['Vampire is a scenario-local callsign'] },
    { bundleId: 'formation:india-rafale-ambala', modelAssetRef: 'model:rafale', routeAssetRefs: ['trajectory:ambala-rafale-1', 'trajectory:ambala-rafale-2', 'trajectory:ambala-rafale-3', 'trajectory:ambala-rafale-4'], semanticEntityAliases: ['Rafale', 'Rafale编队', '阵风', '阵风战斗机', '阵风编队'], behaviorProfileRefs: ['fighter-formation/v1'], locationRefs: ['location:ambala', 'AMBALA', 'Ambala', '安巴拉'], diagnostics: [] },
    { bundleId: 'formation:pakistan-jf17-minhas', modelAssetRef: 'model:jf17', routeAssetRefs: ['trajectory:minhas-j10ce-1', 'trajectory:minhas-j10ce-2', 'trajectory:minhas-j10ce-3', 'trajectory:minhas-j10ce-4'], semanticEntityAliases: ['JF-17', 'JF-17战机', 'JF-17编队', 'JF17'], behaviorProfileRefs: ['fighter-formation/v1'], locationRefs: ['location:minhas', 'location:minas', 'MINHAS', 'MINAS', 'Minhas', 'Minas', '米纳斯'], diagnostics: ['Operator route label is J-10CE', 'OPERATOR_ROUTE_LABEL_DIFFERS_FROM_REPORT_ENTITY'] },
    { bundleId: 'formation:pakistan-jf17-rafiki', modelAssetRef: 'model:jf17', routeAssetRefs: ['trajectory:rafiki-j10ce-1', 'trajectory:rafiki-j10ce-2', 'trajectory:rafiki-j10ce-3', 'trajectory:rafiki-j10ce-4'], semanticEntityAliases: ['JF-17', 'JF-17战机', 'JF-17编队', 'JF17'], behaviorProfileRefs: ['fighter-formation/v1'], locationRefs: ['location:rafiki', 'RAFIKI', 'Rafiki', '拉菲基'], diagnostics: ['Operator route label is J-10CE', 'OPERATOR_ROUTE_LABEL_DIFFERS_FROM_REPORT_ENTITY'] },
    { bundleId: 'reserve:india-su30-ambala', modelAssetRef: 'model:su30mki', routeAssetRefs: ['trajectory:ambala-su30mki-1', 'trajectory:ambala-su30mki-2'], semanticEntityAliases: ['Su-30MKI', '苏-30MKI'], behaviorProfileRefs: ['fighter-formation/v1'], locationRefs: ['location:ambala', 'AMBALA', 'Ambala', '安巴拉'], diagnostics: ['Reserve capacity; does not create actors'] },
    { bundleId: 'support:india-netra-awacs', modelAssetRef: 'model:netra-awacs', routeAssetRefs: ['trajectory:india-awacs-1'], semanticEntityAliases: ['Netra AEW&CS', 'Netra', '印方预警机', '印度预警机'], behaviorProfileRefs: ['awacs-support/india/v1'], locationRefs: [], diagnostics: [] },
    { bundleId: 'support:pakistan-awacs-proxy', modelAssetRef: 'model:awacs-generic-e3a', routeAssetRefs: ['trajectory:pakistan-awacs-1'], semanticEntityAliases: ['巴方预警机（通用示意模型）', '巴方预警机', '巴基斯坦预警机', 'Saab 2000 Erieye', 'ZDK-03'], behaviorProfileRefs: ['awacs-support/pakistan/v1'], locationRefs: [], diagnostics: ['Boeing E-3A is a visual proxy only'] },
    { bundleId: 'weapon:india-first-strike', modelAssetRef: 'model:pl15e', routeAssetRefs: ['trajectory:india-missile-1', 'trajectory:pakistan-missile-1', 'trajectory:pakistan-strike-missile-2'], semanticEntityAliases: ['missile', 'PL-15E', 'PL-15E导弹', '导弹'], behaviorProfileRefs: ['weapon-launch/india-first-strike/v1'], locationRefs: [], diagnostics: [] },
    { bundleId: 'weapon:pakistan-intercept', modelAssetRef: 'model:pl15e', routeAssetRefs: ['trajectory:pakistan-missile-1', 'trajectory:pakistan-strike-missile-2', 'trajectory:india-missile-1'], semanticEntityAliases: ['missile', 'PL-15E', 'PL-15E导弹', '导弹'], behaviorProfileRefs: ['weapon-launch/pakistan-intercept/v1'], locationRefs: [], diagnostics: [] },
    { bundleId: 'weapon:pakistan-counterattack', modelAssetRef: 'model:pl15e', routeAssetRefs: ['trajectory:pakistan-strike-missile-2', 'trajectory:pakistan-missile-1', 'trajectory:india-missile-1'], semanticEntityAliases: ['missile', 'PL-15E', 'PL-15E导弹', '导弹'], behaviorProfileRefs: ['weapon-launch/pakistan-counterattack/v1'], locationRefs: [], diagnostics: [] },
  ],
  mediaProfiles: [],
  actorProfiles: [
    { groupId: 'group:india-su30-adampur', semanticEntityRef: '苏-30MKI', aliases: ['Su-30MKI', '苏-30MKI'], factionId: 'india', locationAliases: ['Adampur', '阿达姆普尔'], locationRef: 'location:adampur', platformType: '苏-30MKI', role: 'fighter-formation', formationPattern: 'finger-four', leaderPolicy: 'stable-first-member', behaviorProfile: 'fighter-formation/v1', linkedEvidenceOnly: false, participantAliases: ['Su-30MKI', '苏-30MKI', '印方编队'], sharedEvidenceAliases: [], diagnostics: [{ code: 'SCENARIO_LOCAL_CALLSIGN_MAPPING', message: 'Vampire is a scenario-local Su-30MKI callsign, not a global synonym.' }] },
    { groupId: 'group:india-rafale-ambala', semanticEntityRef: '阵风', aliases: ['Rafale', '阵风'], factionId: 'india', locationAliases: ['Ambala', '安巴拉'], locationRef: 'location:ambala', platformType: '阵风', role: 'fighter-formation', formationPattern: 'finger-four', leaderPolicy: 'stable-first-member', behaviorProfile: 'fighter-formation/v1', linkedEvidenceOnly: false, participantAliases: ['Rafale', '阵风', '印方编队'], sharedEvidenceAliases: [], diagnostics: [] },
    { groupId: 'group:pakistan-jf17-minhas', semanticEntityRef: 'JF-17', aliases: ['JF-17', 'JF17'], factionId: 'pakistan', locationAliases: ['Minhas', 'Minas', '米纳斯'], locationRef: 'location:minhas', platformType: 'JF-17', role: 'fighter-formation', formationPattern: 'finger-four', leaderPolicy: 'stable-first-member', behaviorProfile: 'fighter-formation/v1', linkedEvidenceOnly: false, participantAliases: ['JF-17', 'JF17', '巴方编队', '巴方拦截编队'], sharedEvidenceAliases: [], diagnostics: [{ code: 'OPERATOR_ROUTE_LABEL_DIFFERS_FROM_REPORT_ENTITY', message: 'Current-scenario J-10CE route labels map to report JF-17 actors without creating a global synonym.' }] },
    { groupId: 'group:pakistan-jf17-rafiki', semanticEntityRef: 'JF-17', aliases: ['JF-17', 'JF17'], factionId: 'pakistan', locationAliases: ['Rafiki', '拉菲基'], locationRef: 'location:rafiki', platformType: 'JF-17', role: 'fighter-formation', formationPattern: 'finger-four', leaderPolicy: 'stable-first-member', behaviorProfile: 'fighter-formation/v1', linkedEvidenceOnly: false, participantAliases: ['JF-17', 'JF17', '巴方编队', '巴方拦截编队'], sharedEvidenceAliases: [], diagnostics: [{ code: 'OPERATOR_ROUTE_LABEL_DIFFERS_FROM_REPORT_ENTITY', message: 'Current-scenario J-10CE route labels map to report JF-17 actors without creating a global synonym.' }] },
    { groupId: 'group:india-netra-awacs', semanticEntityRef: 'Netra AEW&CS', aliases: ['Netra AEW&CS', 'Netra', '印方预警机', '印度预警机'], factionId: 'india', locationAliases: [], locationRef: 'location:india-awacs', platformType: 'awacs', role: 'early-warning-support', formationPattern: 'single', leaderPolicy: 'single-member', behaviorProfile: 'awacs-support/india/v1', linkedEvidenceOnly: true, participantAliases: ['Netra AEW&CS', 'Netra', '印方预警机'], sharedEvidenceAliases: ['Indian and Pakistani AWACS', '双方预警机', '印巴双方预警机'], diagnostics: [] },
    { groupId: 'group:pakistan-awacs-proxy', semanticEntityRef: '巴方预警机（通用示意模型）', aliases: ['巴方预警机', '巴基斯坦预警机', 'Saab 2000 Erieye', 'ZDK-03'], factionId: 'pakistan', locationAliases: [], locationRef: 'location:pakistan-awacs', platformType: 'awacs', role: 'early-warning-support', formationPattern: 'single', leaderPolicy: 'single-member', behaviorProfile: 'awacs-support/pakistan/v1', linkedEvidenceOnly: true, participantAliases: ['巴方预警机', 'Saab 2000 Erieye', 'ZDK-03'], sharedEvidenceAliases: ['Indian and Pakistani AWACS', '双方预警机', '印巴双方预警机'], diagnostics: [] },
  ],
  weaponBehaviorProfiles: [{ factionId: 'india', behaviorProfile: 'weapon-launch/india-first-strike/v1', matchTerms: [] }, { factionId: 'pakistan', behaviorProfile: 'weapon-launch/pakistan-intercept/v1', matchTerms: ['intercept', 'incoming missile', '拦截', '来袭导弹'] }, { factionId: 'pakistan', behaviorProfile: 'weapon-launch/pakistan-counterattack/v1', matchTerms: ['counterattack', 'rafale', '反击'] }],
} as const satisfies ScenarioPack
